Repository GoogleChrome/workbox, pull requests merged in 2018-10, with the labels that each got.

#1673 Add deferred udpates and postMessage fallback
  infra/testing/sw-env-mocks/ExtendableMessageEvent.js
  infra/testing/sw-env.js
  packages/workbox-broadcast-cache-update/BroadcastCacheUpdate.mjs
  packages/workbox-broadcast-cache-update/Plugin.mjs
  packages/workbox-broadcast-cache-update/_public.mjs
  packages/workbox-broadcast-cache-update/broadcastUpdate.mjs
  packages/workbox-broadcast-cache-update/responsesAreSame.mjs
  packages/workbox-broadcast-cache-update/utils/constants.mjs
  packages/workbox-core/_private/Deferred.mjs
  packages/workbox-core/_private/cacheWrapper.mjs
  test/workbox-broadcast-cache-update/node/test-BroadcastCacheUpdate.mjs
  test/workbox-broadcast-cache-update/node/test-Plugin.mjs
  test/workbox-broadcast-cache-update/node/test-broadcastUpdate.mjs
  test/workbox-broadcast-cache-update/node/test-responsesAreSame.mjs
  test/workbox-broadcast-cache-update/static/index.html
  test/workbox-broadcast-cache-update/static/sw.js
  test/workbox-core/node/_private/test-Deferred.mjs
Labels: Breaking Change

#1657 Consistently reject with a WorkboxError when a strategy fails
  package-lock.json
  packages/workbox-core/models/messages/messages.mjs
  packages/workbox-strategies/CacheFirst.mjs
  packages/workbox-strategies/CacheOnly.mjs
  packages/workbox-strategies/NetworkFirst.mjs
  packages/workbox-strategies/NetworkOnly.mjs
  packages/workbox-strategies/StaleWhileRevalidate.mjs
  test/workbox-strategies/node/test-CacheFirst.mjs
  test/workbox-strategies/node/test-CacheOnly.mjs
  test/workbox-strategies/node/test-NetworkFirst.mjs
  test/workbox-strategies/node/test-NetworkOnly.mjs
  test/workbox-strategies/node/test-StaleWhileRevalidate.mjs
Labels: Breaking Change

#1679 Precache manifest.json by default when using the webpack plugin
  packages/workbox-webpack-plugin/src/lib/get-default-config.js
  test/workbox-webpack-plugin/node/generate-sw.js
  test/workbox-webpack-plugin/node/inject-manifest.js
Labels: Breaking Change

#1682 Decouple Router~handleRequest from events
  packages/workbox-build/package-lock.json
  packages/workbox-google-analytics/initialize.mjs
  packages/workbox-routing/NavigationRoute.mjs
  packages/workbox-routing/Router.mjs
  packages/workbox-routing/_default.mjs
  packages/workbox-routing/_types.mjs
  packages/workbox-strategies/CacheFirst.mjs
  packages/workbox-strategies/CacheOnly.mjs
  packages/workbox-strategies/NetworkFirst.mjs
  packages/workbox-strategies/NetworkOnly.mjs
  packages/workbox-strategies/StaleWhileRevalidate.mjs
  packages/workbox-webpack-plugin/package-lock.json
  test/workbox-routing/node/test-NavigationRoute.mjs
  test/workbox-routing/node/test-Router.mjs
  test/workbox-routing/node/test-default.mjs
  test/workbox-strategies/node/test-UsageWithRouter.mjs
Labels: Breaking Change, workbox-routing, workbox-strategies

#1716 Fail SW installation when a precaching request results in an error response
  packages/workbox-core/models/messages/messages.mjs
  packages/workbox-precaching/_default.mjs
  packages/workbox-precaching/controllers/PrecacheController.mjs
  test/workbox-precaching/node/controllers/test-PrecacheController.mjs
Labels: Breaking Change

#1721 workbox-range-requests will return a 206 response as-is
  packages/workbox-range-requests/createPartialResponse.mjs
  test/workbox-range-requests/node/createPartialResponse.mjs
Labels: Breaking Change

#1736 Delete temporary precache after SW activation
  packages/workbox-precaching/controllers/PrecacheController.mjs
  test/workbox-precaching/node/controllers/test-PrecacheController.mjs
Labels: workbox-precaching
